################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Src/lvgl/src/core \
Core/Src/lvgl/src/display \
Core/Src/lvgl/src/draw/dma2d \
Core/Src/lvgl/src/draw \
Core/Src/lvgl/src/draw/nema_gfx \
Core/Src/lvgl/src/draw/nxp/pxp \
Core/Src/lvgl/src/draw/nxp/vglite \
Core/Src/lvgl/src/draw/opengles \
Core/Src/lvgl/src/draw/renesas/dave2d \
Core/Src/lvgl/src/draw/sdl \
Core/Src/lvgl/src/draw/sw/blend/helium \
Core/Src/lvgl/src/draw/sw/blend \
Core/Src/lvgl/src/draw/sw/blend/neon \
Core/Src/lvgl/src/draw/sw \
Core/Src/lvgl/src/draw/vg_lite \
Core/Src/lvgl/src/drivers/display/drm \
Core/Src/lvgl/src/drivers/display/fb \
Core/Src/lvgl/src/drivers/display/ili9341 \
Core/Src/lvgl/src/drivers/display/lcd \
Core/Src/lvgl/src/drivers/display/renesas_glcdc \
Core/Src/lvgl/src/drivers/display/st7735 \
Core/Src/lvgl/src/drivers/display/st7789 \
Core/Src/lvgl/src/drivers/display/st7796 \
Core/Src/lvgl/src/drivers/display/st_ltdc \
Core/Src/lvgl/src/drivers/evdev \
Core/Src/lvgl/src/drivers/glfw \
Core/Src/lvgl/src/drivers/libinput \
Core/Src/lvgl/src/drivers/nuttx \
Core/Src/lvgl/src/drivers/qnx \
Core/Src/lvgl/src/drivers/sdl \
Core/Src/lvgl/src/drivers/wayland \
Core/Src/lvgl/src/drivers/windows \
Core/Src/lvgl/src/drivers/x11 \
Core/Src/lvgl/src/font \
Core/Src/lvgl/src/indev \
Core/Src/lvgl/src/layouts/flex \
Core/Src/lvgl/src/layouts/grid \
Core/Src/lvgl/src/layouts \
Core/Src/lvgl/src/libs/barcode \
Core/Src/lvgl/src/libs/bin_decoder \
Core/Src/lvgl/src/libs/bmp \
Core/Src/lvgl/src/libs/ffmpeg \
Core/Src/lvgl/src/libs/freetype \
Core/Src/lvgl/src/libs/fsdrv \
Core/Src/lvgl/src/libs/gif \
Core/Src/lvgl/src/libs/libjpeg_turbo \
Core/Src/lvgl/src/libs/libpng \
Core/Src/lvgl/src/libs/lodepng \
Core/Src/lvgl/src/libs/lz4 \
Core/Src/lvgl/src/libs/qrcode \
Core/Src/lvgl/src/libs/rle \
Core/Src/lvgl/src/libs/rlottie \
Core/Src/lvgl/src/libs/svg \
Core/Src/lvgl/src/libs/tiny_ttf \
Core/Src/lvgl/src/libs/tjpgd \
Core/Src/lvgl/src \
Core/Src/lvgl/src/misc/cache \
Core/Src/lvgl/src/misc \
Core/Src/lvgl/src/osal \
Core/Src/lvgl/src/others/file_explorer \
Core/Src/lvgl/src/others/font_manager \
Core/Src/lvgl/src/others/fragment \
Core/Src/lvgl/src/others/gridnav \
Core/Src/lvgl/src/others/ime \
Core/Src/lvgl/src/others/imgfont \
Core/Src/lvgl/src/others/monkey \
Core/Src/lvgl/src/others/observer \
Core/Src/lvgl/src/others/snapshot \
Core/Src/lvgl/src/others/sysmon \
Core/Src/lvgl/src/others/vg_lite_tvg \
Core/Src/lvgl/src/stdlib/builtin \
Core/Src/lvgl/src/stdlib/clib \
Core/Src/lvgl/src/stdlib \
Core/Src/lvgl/src/stdlib/micropython \
Core/Src/lvgl/src/stdlib/rtthread \
Core/Src/lvgl/src/themes/default \
Core/Src/lvgl/src/themes \
Core/Src/lvgl/src/themes/mono \
Core/Src/lvgl/src/themes/simple \
Core/Src/lvgl/src/tick \
Core/Src/lvgl/src/widgets/animimage \
Core/Src/lvgl/src/widgets/arc \
Core/Src/lvgl/src/widgets/bar \
Core/Src/lvgl/src/widgets/button \
Core/Src/lvgl/src/widgets/buttonmatrix \
Core/Src/lvgl/src/widgets/calendar \
Core/Src/lvgl/src/widgets/canvas \
Core/Src/lvgl/src/widgets/chart \
Core/Src/lvgl/src/widgets/checkbox \
Core/Src/lvgl/src/widgets/dropdown \
Core/Src/lvgl/src/widgets/image \
Core/Src/lvgl/src/widgets/imagebutton \
Core/Src/lvgl/src/widgets/keyboard \
Core/Src/lvgl/src/widgets/label \
Core/Src/lvgl/src/widgets/led \
Core/Src/lvgl/src/widgets/line \
Core/Src/lvgl/src/widgets/list \
Core/Src/lvgl/src/widgets/lottie \
Core/Src/lvgl/src/widgets/menu \
Core/Src/lvgl/src/widgets/msgbox \
Core/Src/lvgl/src/widgets/objx_templ \
Core/Src/lvgl/src/widgets/property \
Core/Src/lvgl/src/widgets/roller \
Core/Src/lvgl/src/widgets/scale \
Core/Src/lvgl/src/widgets/slider \
Core/Src/lvgl/src/widgets/span \
Core/Src/lvgl/src/widgets/spinbox \
Core/Src/lvgl/src/widgets/spinner \
Core/Src/lvgl/src/widgets/switch \
Core/Src/lvgl/src/widgets/table \
Core/Src/lvgl/src/widgets/tabview \
Core/Src/lvgl/src/widgets/textarea \
Core/Src/lvgl/src/widgets/tileview \
Core/Src/lvgl/src/widgets/win \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \

